# Single Neuron, Perceptron

In [23]:
import torch
import torch.nn as nn

In [24]:
torch.manual_seed(42)

In [25]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
inputs


tensor([1., 2., 3., 4.])

In [26]:
neuron = nn.Linear(in_features=4, out_features=1)
neuron

Linear(in_features=4, out_features=1, bias=True)

In [27]:
output = neuron(inputs)
output

tensor([2.5885], grad_fn=<ViewBackward0>)

In [28]:
# verify.... formula

neuron.weight @ inputs + neuron.bias

tensor([2.5885], grad_fn=<AddBackward0>)

In [29]:
neuron.bias

Parameter containing:
tensor([-0.1096], requires_grad=True)